In [3]:
url='https://becas.osinergmin.gob.pe/seccion/centro_documental/hidrocarburos/SCOP/SCOP-DOCS/2022/01-Demanda-Nacional-Combustibles-Liquidos-Enero-2022.pdf'

In [7]:
from tabula import read_pdf
import tabula as tb

In [11]:
df=read_pdf(url, pages=1)
df

[       Unnamed: 0        Gas  Unnamed: 1 Gasolina Gasolina.1 Gasolina.2  \
 0    DEPARTAMENTO        NaN         NaN      NaN        NaN        NaN
 1             NaN  100LL (*)         NaN       84         90         95
 2        AMAZONAS          0         NaN    3,439     20,347      2,560
 3          ANCASH          0         NaN      NaN        NaN        NaN
 4        APURIMAC          0         NaN      NaN        NaN        NaN
 5        AREQUIPA          0         NaN      NaN        NaN        NaN
 6        AYACUCHO          0         NaN      NaN        NaN        NaN
 7       CAJAMARCA          0         NaN      NaN        NaN        NaN
 8           CUSCO          0         NaN      NaN        NaN        NaN
 9    HUANCAVELICA          0         NaN      NaN        NaN        NaN
 10        HUANUCO          0         NaN      NaN        NaN        NaN
 11            ICA          0         NaN      NaN        NaN        NaN
 12          JUNIN          0         NaN      NaN        NaN        NaN
 13    LA LIBERTAD          0         NaN      NaN        NaN        NaN
 14     LAMBAYEQUE          0         NaN      NaN        NaN        NaN
 15           LIMA         48         NaN        0          0          0
 16         LORETO        173         NaN   86,584     24,899        129
 17  MADRE DE DIOS          0         NaN   36,556      3,827      1,226
 18       MOQUEGUA          0         NaN      NaN        NaN        NaN
 19          PASCO          0         NaN      NaN        NaN        NaN
 20          PIURA          0         NaN      NaN        NaN        NaN
 21           PUNO          0         NaN      NaN        NaN        NaN
 22     SAN MARTIN         97         NaN   13,485     52,012      3,371
 23          TACNA          0         NaN      NaN        NaN        NaN
 24         TUMBES          0         NaN      NaN        NaN        NaN
 25        UCAYALI         97         NaN      NaN     86,245        710
 26          TOTAL        415         NaN  140,065    187,330      7,995
 27     TOTAL MBPD       0.01         NaN     3.33       4.46       0.19

     Gasolina.3  Unnamed: 2      Total Gasohol 84  ... Unnamed: 6 Unnamed: 7  \
 0          NaN         NaN        NaN        NaN  ...        NaN   DB5 S-50
 1        97.00         NaN  Gasolinas       Plus  ...        NaN        NaN
 2          NaN         NaN     26,346        155  ...        NaN     27,917
 3          NaN         NaN          0         81  ...        NaN    334,629
 4          NaN         NaN          0         32  ...        NaN    211,141
 5          NaN         NaN          0        687  ...        NaN    601,953
 6          NaN         NaN          0        344  ...        NaN     75,010
 7          NaN         NaN          0      5,404  ...        NaN    147,205
 8          NaN         NaN          0      2,200  ...        NaN    281,040
 9          NaN         NaN          0         16  ...        NaN     15,123
 10         NaN         NaN          0        NaN  ...        NaN     41,542
 11         NaN         NaN          0      2,295  ...        NaN    262,205
 12         NaN         NaN          0      1,252  ...        NaN    194,764
 13         NaN         NaN          0      3,153  ...        NaN    321,383
 14         NaN         NaN          0     12,829  ...        NaN    140,952
 15        0.00         NaN          0        919  ...        NaN  1,231,355
 16         NaN         NaN    111,612        NaN  ...        NaN         13
 17         NaN         NaN     41,609        NaN  ...        NaN    211,544
 18         NaN         NaN          0        323  ...        NaN    477,495
 19         NaN         NaN          0        360  ...        NaN     50,520
 20         NaN         NaN          0     14,820  ...        NaN    228,222
 21         NaN         NaN          0     26,247  ...        NaN    155,441
 22      410.00         NaN     69,278         65  ...        NaN     54,210
 23         NaN         NaN          0        380  ...        NaN     62,032
 24         NaN         NaN          0      5,360  ...        NaN      8,451
 25         NaN         NaN     86,955        NaN  ...        NaN         97
 26      410.00         NaN    335,800     76,921  ...        NaN  5,134,244
 27        0.01         NaN       8.00       1.83  ...        NaN     122.24

    Pet Ind Pet Ind.1 Pet Ind.2 Unnamed: 8    Diesel  Unnamed: 9 Unnamed: 10  \
 0      NaN       NaN       NaN        NaN       NaN         IFO         NaN
 1   No 500      No 6      No 5        NaN  MGO(***)         NaN         NaN
 2      NaN       NaN       NaN        NaN       NaN         NaN         NaN
 3      414     3,969       NaN        NaN       NaN         NaN         NaN
 4      NaN       NaN       NaN        NaN       NaN         NaN         NaN
 5   12,674       820       NaN        NaN       NaN         NaN         NaN
 6      NaN       NaN       NaN        NaN       NaN         NaN         NaN
 7      NaN       NaN       NaN        NaN       NaN         NaN         NaN
 8      NaN       NaN       NaN        NaN       NaN         NaN         NaN
 9      NaN       NaN       NaN        NaN       NaN         NaN         NaN
 10     NaN       NaN       NaN        NaN       NaN         NaN         NaN
 11     NaN       NaN       NaN        NaN       NaN         NaN         NaN
 12     NaN       NaN       NaN        NaN       NaN         NaN         NaN
 13     NaN     3,270       NaN        NaN       NaN         NaN         NaN
 14     NaN       NaN       NaN        NaN       NaN         NaN         NaN
 15   3,254     1,522       NaN        NaN     1,081         NaN         NaN
 16     NaN    55,838       NaN        NaN       NaN         NaN         NaN
 17     NaN       NaN       NaN        NaN       NaN         NaN         NaN
 18   2,310     1,370       NaN        NaN       NaN         NaN         NaN
 19     NaN       NaN       NaN        NaN       NaN         NaN         NaN
 20     NaN     2,345       NaN        NaN       NaN         NaN         NaN
 21     NaN       NaN       NaN        NaN       NaN         NaN         NaN
 22     NaN       NaN       NaN        NaN       NaN         NaN         NaN
 23     NaN       NaN       NaN        NaN       NaN         NaN         NaN
 24     NaN       NaN       NaN        NaN       NaN         NaN         NaN
 25     NaN       NaN       NaN        NaN     1,343         NaN         NaN
 26  18,651    69,134         0        NaN     2,424           0         NaN
 27    0.44      1.65      0.00        NaN      0.06        0.00         NaN

     Unnamed: 11
 0         TOTAL
 1           NaN
 2        56,578
 3       396,264
 4       236,509
 5       781,162
 6       118,647
 7       216,291
 8       401,830
 9        27,462
 10       72,869
 11      343,632
 12      277,503
 13      434,681
 14      230,504
 15    2,511,055
 16      255,947
 17      253,153
 18      501,445
 19       68,698
 20      380,089
 21      238,580
 22      128,295
 23       89,752
 24       21,905
 25      183,134
 26    8,225,984
 27       195.86

 [28 rows x 29 columns]]